### 전체메모리스트
GET http://localhost:8080/api/memos


### id에 해당하는 메모
GET http://localhost:8080/api/memos/1

### 메모생성
POST http://localhost:8080/api/memos
Content-Type: application/json

{
  "memo": "첫번째 메모"
}

### 메모생성
POST http://localhost:8080/api/memos
Content-Type: application/json

{
  "memo": "두번째 메모"
}

### 메모생성
POST http://localhost:8080/api/memos
Content-Type: application/json

{
  "memo": "세번째 메모"
}

### 메모수정
PUT http://localhost:8080/api/memos/1
Content-Type: application/json

{
  "memo": "수정된 메모1"
}

### 메모수정 - 없는 아이디 호출
PUT http://localhost:8080/api/memos/11
Content-Type: application/json

{
  "memo": "수정된 메모1"
}

### 메모삭제
DELETE http://localhost:8080/api/memos/1
Accept: application/json