spring:
  application:
    name: securityexam

  datasource:
    url: jdbc:mysql://localhost:3306/caramidb
    username: carami
    password: carami1234

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liSsdQxWkfHO9tXT
            client-secret: 59411c35f2a07b889edc4c6f2d239ade4b772124
            scope:
              - read:user
              - user:email


jwt:
  secretKey: aPQbsKV7CZZDls/cnhW1EjqlGux45LAbBYpBhyk7nAk=
  refreshKey: 123456789010123456789023u454954958495w43434
  access-expiration-ms: 10000
  refresh-expiration-ms: 604800000

#  security:
#    user:
#      name: carami
#      password: 1234



logging:
  level:
    org:
      springframework:
        security: trace



server:
  tomcat:
    threads:
      max: 200
      min-spare: 5

