apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: myapp # 네임스페이스 지정
type: Opaque
data:
  # base64로 인코딩된 값
  # echo -n 'rootpassword' | base64 → cm9vdHBhc3N3b3Jk
  # echo -n 'myapppassword' | base64 → bXlhcHBwYXNzd29yZA==
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-password: bXlhcHBwYXNzd29yZA==