apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: myapp # 네임스페이스 지정
type: Opaque
stringData: # stringData는 base64 인코딩 없이 직접 입력 가능
  spring-datasource-url: "jdbc:mysql://mysql-service:3306/myappdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
  spring-datasource-username: "myappuser"
  spring-datasource-password: "myapppassword"