### 로그인 [실패]  - 값이 없이 들어왔을때.
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "password": "1111"
}

### 로그인 [실패]  - 값이 없이 들어왔을때.
POST http://localhost:8080/api/login
Content-Type: application/json

{
}

### 로그인 [실패] 1. 비밀번호가 틀렸을때.
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "carami",
  "password": "22"
}


### 로그인 [성공] 2. 정상로그인(토큰발급)
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "woong",
  "password": "1234"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}




### welcome  -- 토큰없이 요청
# @no-cookie-jar
GET http://localhost:8080/api/welcome


### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Cookie: accessToken={{accessToken}}


### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Authorization: Bearer {{accessToken}}


### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Authorization: Bearer {{accessToken}}te



### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrYW5nIiwiZW1haWwiOiJrYW5nQGthbmcuY29tIiwibmFtZSI6Imthbmcga20iLCJ1c2VySWQiOjIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzgxODQyNzA1LCJleHAiOjE3ODE4NDQ1MDV9.ZDIvYTNU59ZxKBdbrl6ZF59lHpYPwkREogJKVlvdb0Q

### 리프레시토큰 테스트
# access토큰의 만료시간을 짧게 수정하고 서버를 재시작함.(10초) 10000
# 10초 기다렸다가 다시 요청.  ### @no-cookie-jar
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Cookie: accessToken={{accessToken}}

### 리프레시토큰으로 엑세스토큰 갱신
# @no-cookie-jar
POST http://localhost:8080/api/refreshToken
Cookie: refreshToken={{refreshToken}}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

