### 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "carami",
  "password": "1111"
}

### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome




### welcome
# @no-cookie-jar
GET http://localhost:8080/api/welcome
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrYW5nIiwiZW1haWwiOiJrYW5nQGthbmcuY29tIiwibmFtZSI6Imthbmcga20iLCJ1c2VySWQiOjIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzgxODQyNzA1LCJleHAiOjE3ODE4NDQ1MDV9.ZDIvYTNU59ZxKBdbrl6ZF59lHpYPwkREogJKVlvdb0Q