apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-secret-demo
  template:
    metadata:
      labels:
        app: config-secret-demo
    spec:
      containers:
      - name: node-container
        image: busybox
        command: ["/bin/sh", "-c", "echo WELCOME=$WELCOME_MESSAGE APP=$APP_MODE PASS=$DB_PASSWORD && sleep 3600"]
        ports:
        - containerPort: 3000
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: my-config       # ConfigMap 이름
              key: WELCOME_MESSAGE  # ConfigMap 내 키
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: APP_MODE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret      # Secret 이름
              key: DB_PASSWORD     # Secret 내 키