---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - port: 80            # Service가 클러스터 내부에서 제공할 포트
      targetPort: 80      # Pod(nginx)에서 열려있는 포트
      nodePort: 30080     # (선택) NodePort 직접 지정 (30000~32767 범위)