apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: app-container
    image: busybox
    command: [ "/bin/sh", "-c", "echo $WELCOME_MESSAGE && echo $APP_MODE && sleep 3600" ]
    env:
    - name: WELCOME_MESSAGE
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: WELCOME_MESSAGE
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_MODE