apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data        # 노드의 로컬 디렉토리 (테스트용)
  persistentVolumeReclaimPolicy: Retain