spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TodoDB
    username: todo
    password: todo1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true